auth0:
  audience: https://taskmanager.com
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task-manager
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://richmond-task-manager.us.auth0.com/
  # JPA properties
  jpa:
    hibernate:
    ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true